/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.20                          *
*        Compiled Mar 19 2013, 15:01:00                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "includes.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x0A)
#define ID_TEXT_1 (GUI_ID_USER + 0x0B)
#define ID_TEXT_2 (GUI_ID_USER + 0x0C)
#define ID_TEXT_3 (GUI_ID_USER + 0x0D)
#define ID_TEXT_4 (GUI_ID_USER + 0x0E)
#define ID_TEXT_5 (GUI_ID_USER + 0x0F)
#define ID_EDIT_0 (GUI_ID_USER + 0x12)
#define ID_EDIT_1 (GUI_ID_USER + 0x13)
#define ID_EDIT_2 (GUI_ID_USER + 0x14)
#define ID_EDIT_3 (GUI_ID_USER + 0x15)
#define ID_EDIT_4 (GUI_ID_USER + 0x16)
#define ID_EDIT_5 (GUI_ID_USER + 0x17)
#define ID_BUTTON_0 (GUI_ID_USER + 0x1A)
#define ID_BUTTON_1 (GUI_ID_USER + 0x1B)
#define ID_BUTTON_2 (GUI_ID_USER + 0x1C)

#define ID_TEXT_6  (GUI_ID_USER + 0x1D)
#define ID_EDIT_6  (GUI_ID_USER + 0x1E)

#define ID_TEXT_7  (GUI_ID_USER + 0x1F)
#define ID_EDIT_7  (GUI_ID_USER + 0x20)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/


//{ EDIT_CreateIndirect,   "edit", ID_EDIT_0, 155, 10, 80, 20, 0, 0x64, 0 },
  //{ EDIT_CreateIndirect,   "edit",          ID_EDIT_1, 155, 40, 80, 20, 0, 0x64, 0 },
  //{ EDIT_CreateIndirect, "addr",             ID_EDIT_2, 155, 70, 80, 20, 0, 0x64, 0 },
 // { TEXT_CreateIndirect, InterElecPrt,          ID_TEXT_0, 7, 10, 122, 20, 0, 0x0, 0 },
 // { TEXT_CreateIndirect, ProtectTime,    ID_TEXT_1,   5,   40,  128, 20, 0, 0x0, 0 },
 // { TEXT_CreateIndirect, DevAddr,          ID_TEXT_2, 5, 71, 80, 20, 0, 0x0, 0 },




static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "SysCtl", ID_WINDOW_0,     0,   0,   240, 295,0, 0x0, 0 },
  { TEXT_CreateIndirect, "EEPROM",       ID_TEXT_0,   8,   11,  80,  20, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, RelaySwitch,    ID_TEXT_1,   8,   38,  120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, ContactorState, ID_TEXT_2,   8,   38,  120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, ProtectNum,     ID_TEXT_3,   8,   70,  120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, Voltage,        ID_TEXT_4,   8,   97, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, ProtectTime,    ID_TEXT_5,   8,   126, 125, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, DevAddr,        ID_TEXT_6,   8,   156, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, InterElecPrt,        ID_TEXT_7,   8,   186, 120, 20, 0, 0x0, 0 },

  
  { EDIT_CreateIndirect, "Edit",         ID_EDIT_0,   153, 6,   80, 20, EDIT_CF_HCENTER, 0x64, 0 },
  //{ EDIT_CreateIndirect, "Edit",         ID_EDIT_1,   153, 35,  80, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit",         ID_EDIT_2,   153, 35,  80, 20, EDIT_CF_HCENTER, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit",         ID_EDIT_3,   153, 64,  80, 20, EDIT_CF_HCENTER, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit",         ID_EDIT_4,   153, 93, 80, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit",         ID_EDIT_5,   153, 121, 80, 20, EDIT_CF_HCENTER, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit",         ID_EDIT_6,   153, 150, 80, 20, EDIT_CF_HCENTER, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit",         ID_EDIT_7,   153, 179, 80, 20, EDIT_CF_HCENTER, 0x64, 0 },

  { BUTTON_CreateIndirect, ReadData,         ID_BUTTON_0, 7,   260, 60, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, Quit,         ID_BUTTON_2, 172, 260, 60, 25, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, ReadSysState,   ID_TEXT_5,   8,   126, 100, 20, 0, 0x0, 0 },
  //{ BUTTON_CreateIndirect, "F1",         ID_BUTTON_1, 153,  126, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static void _init_SysCtlDialog(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;

    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, " ");
    WM_DisableWindow(hItem);

    //hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    //EDIT_SetText(hItem, " ");
    //WM_DisableWindow(hItem);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, " ");
    WM_DisableWindow(hItem);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, " ");
    WM_DisableWindow(hItem);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_7);
    EDIT_SetText(hItem, " ");
    WM_DisableWindow(hItem);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetText(hItem, " ");
    WM_DisableWindow(hItem);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_6);
    EDIT_SetText(hItem, " ");
    WM_DisableWindow(hItem);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetFloatMode(hItem, 0.00, 0, 99999, 2, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    WM_DisableWindow(hItem);

    hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0);
    BUTTON_SetBkColor(hItem, 0, GUI_GREEN);
    WIDGET_AndState(hItem, WIDGET_STATE_FOCUSSABLE);

    hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1);
    BUTTON_SetBkColor(hItem, 0, GUI_CYAN);
    WIDGET_AndState(hItem, WIDGET_STATE_FOCUSSABLE);

    hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2);
    BUTTON_SetBkColor(hItem, 0, GUI_YELLOW);
    WIDGET_AndState(hItem, WIDGET_STATE_FOCUSSABLE);

}

WM_HWIN SSD_GetEEPROM(void)
{
    return WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_0);
}

#if 0
WM_HWIN SSD_GetRelaySwitch(void)
{
    return WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_1);
}
#endif

WM_HWIN SSD_GetCtrState(void)
{
    return WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_2);
}

WM_HWIN SSD_GetPrtNum(void)
{
    return WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_3);
}

WM_HWIN SSD_GetPrtSwitch(void)
{
    return WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_7);
}

WM_HWIN SSD_GetPrtTime(void)
{
    return WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_5);
}

WM_HWIN SSD_GetDevAddr(void)
{
    return WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_6);
}

WM_HWIN SSD_GetVoltage(void)
{
    return WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_4);
}
WM_HWIN SSD_ClearData(void)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_0);
    EDIT_SetText(hItem, "");
    hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_2);
    EDIT_SetText(hItem, "");
    hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_3);
    EDIT_SetText(hItem, "");
    hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_4);
    EDIT_SetFloatMode(hItem, 0.00, 0, 99999, 2, GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_5);
    EDIT_SetText(hItem, "");
    hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_6);
    EDIT_SetText(hItem, "");
    hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_7);
    EDIT_SetText(hItem, "");
    OSTimeDlyHMSM(0, 0, 0, 20);
}

#if 0
static int SSD_KeyCnt = 0;

void SSD_SelectUp(void)
{
    WM_HWIN hItem;
    if(SSD_KeyCnt == 0)
    {
        hItem=WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_3);
        WM_SetFocus(hItem);
        SSD_KeyCnt = (SYS_EDT_NUMBER - 1);
    }
    else
    {
        SSD_KeyCnt--;
        hItem=WM_GetDialogItem(g_hWin_TrmState,(ID_EDIT_0 + SSD_KeyCnt));
        WM_SetFocus(hItem);
    }
}

void SSD_SelectDown(void)
{
    WM_HWIN hItem;
    if(SSD_KeyCnt == (SYS_EDT_NUMBER - 1))
    {
        hItem=WM_GetDialogItem(g_hWin_TrmState,ID_EDIT_0);
        WM_SetFocus(hItem);
        SSD_KeyCnt = 0;
    }
    else
    {
        SSD_KeyCnt++;
        hItem=WM_GetDialogItem(g_hWin_TrmState,(ID_EDIT_0 + SSD_KeyCnt));
        WM_SetFocus(hItem);
    }
}
void SSD_ColorChange(void)
{
    WM_HWIN hItem;
    int i;
    for(i = 0;i < SYS_EDT_NUMBER;i++)
    {
        hItem =  WM_GetDialogItem(g_hWin_TrmState, (ID_EDIT_0 + i));
        if( 1 == WM_HasFocus(hItem))
        {
            EDIT_SetBkColor(hItem, 0, GUI_GREEN);
        }
        else if(0 == WM_HasFocus(hItem))
        {
            EDIT_SetBkColor(hItem, 0, 0xC0C0C0);
        }
    }
}

void SSD_FocusSel(void)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hItem, (ID_EDIT_0 + SSD_KeyCnt));
    WM_SetFocus(hItem);
}


#endif







/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  
  switch (pMsg->MsgId) 
  {
      case WM_INIT_DIALOG:
        _init_SysCtlDialog(pMsg);
        break;
        
      case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id) {}
        break;
        
      case WM_KEY:
        Id    = WM_GetId(pMsg->hWinSrc);
        if(_BUTTON_PRESSED == ((WM_KEY_INFO *)(pMsg->Data.p))->PressedCnt)
        {
            switch(((WM_KEY_INFO *)(pMsg->Data.p))->Key)
            {
                case GUI_KEY_YELLOW:
                    WM_DeleteWindow(g_hWin_TrmState);
                    g_hWin_TrmState=WM_HWIN_NULL;
                    WM_SetFocus(g_hWin_menu);
                    WM_ShowWindow(g_hWin_TimeBar);
                    WM_ShowWindow(g_hWin_Date);
                    //SSD_KeyCnt = 0;
                    break;
                case GUI_KEY_GREEN:
                    g_gui_para.state = FHD_GUI_TRM_STATE;
                    g_gui_para.cmd = FHD_CMD_READ_TRM_STATE;
                    OSMboxPost(g_sys_ctrl.up_mbox, &g_gui_para);
                    break;
#if 0
                case GUI_KEY_UP:
                    SSD_SelectUp();
                    SSD_ColorChange();
                    break;
                case GUI_KEY_DOWN:
                    SSD_SelectDown();
                    SSD_ColorChange();
                    break;
#endif
#if 0 
                case GUI_KEY_F1:
                    g_gui_para.state = FHD_GUI_SYS_STATE;
                    g_gui_para.cmd = FHD_CMD_READ_SYS_STATE;
                    OSMboxPost(g_sys_ctrl.up_mbox, &g_gui_para);                     
                    break;
#endif     
                case GUI_KEY_F2:
                    break;
                case '*':
                    break;
                case '#':
                    break;
            }
        }
        break;
      // USER END
      default:
        WM_DefaultProc(pMsg);
        break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSysState
*/
WM_HWIN CreateTrmState(void);
WM_HWIN CreateTrmState(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, g_hWin_menu, 0, 0);
  return hWin;
}



// USER START (Optionally insert additional public code)

void GUI_Trm_State_Proc(void)
{
    WM_HWIN hItem;
    u8 buf[128];
    

    switch(g_gui_para.cmd)
    {
    case FHD_CMD_READ_TRM_STATE:
        u8 *pdata;
        u32 tmp1, tmp2;
        

        pdata = (u8 *)g_fhdp_para.data_buf;
        
        tmp1 = mb_swap_32((u8 *)pdata);
        pdata += 4;

        tmp2 = (tmp1 >> 0) & 0x00000001; //E2PROM
        if(tmp2)
        {
            sprintf(buf, WorkWrong);
        }
        else
        {
            sprintf(buf, WorkRight);
        }

        hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_0);
        EDIT_SetText(hItem, buf);
        
#if 0
        tmp2 = (tmp1 >> 3) & 0x00000001; //电容继电器
        if(tmp2)
        {
            sprintf(buf, HaveAction);
        }
        else
        {
            sprintf(buf, NoneAction);
        }


        hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_1);
        EDIT_SetText(hItem, buf);
#endif

        tmp2 = (tmp1 >> 4) & 0x00000001; //接触器
        if(tmp2)
        {
            sprintf(buf, SwitchOn);
        }
        else
        {
            sprintf(buf, SwitchOff);
        }

        hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_2);
        EDIT_SetText(hItem, buf);

        hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_4); //电压
        EDIT_SetFloatValue(hItem, ((float)mb_swap_32((u8 *)pdata)) / 100);  
        pdata += 4;

        sprintf(buf, "%d", mb_swap(*((u16 *)pdata))); //晃电保护次数
        pdata += 2;
        
        hItem = WM_GetDialogItem(g_hWin_TrmState, ID_EDIT_3);
        EDIT_SetText(hItem, buf); 
        break;
        
    default:
        break;
    }
}

// USER END

/*************************** End of file ****************************/
